function makeQuestions(unitId, rows) {
  return rows.map(([sentence, answer, options, hint], index) => ({
    id: `${unitId}-${String(index + 1).padStart(2, "0")}`,
    sentence,
    answer,
    options,
    hint,
  }));
}

const unit1Questions = makeQuestions("unit1", [
  ["I ___ an old photo while I was tidying the attic.", "came across", ["came across", "looked up to", "went through", "found out"], "Phrasal verbs"],
  ["The documentary ___ how the unusual lights are formed.", "goes through", ["comes from", "goes through", "looks back", "checks out"], "Phrasal verbs"],
  ["Scientists finally ___ why the lake changes colour.", "found out", ["came up with", "looked up to", "found out", "came from"], "Phrasal verbs"],
  ["This shade of paint ___ a mineral found in the mountains.", "comes from", ["checks out", "comes from", "goes through", "looks up to"], "Phrasal verbs"],
  ["The designer ___ a clever way to capture the colour of the sky.", "came up with", ["came across", "came up with", "looked back", "found out"], "Phrasal verbs"],
  ["You should ___ the exhibition before it closes.", "check out", ["check out", "come from", "look back", "go through"], "Phrasal verbs"],
  ["The article ___ several explanations for the strange storm.", "goes through", ["looks up to", "comes across", "goes through", "finds out"], "Phrasal verbs"],
  ["Many young photographers ___ the artist for her originality.", "look up to", ["look back", "look up to", "check out", "come from"], "Phrasal verbs"],
  ["When I ___ on the trip, the glowing waves were the highlight.", "look back", ["find out", "look back", "come up with", "go through"], "Phrasal verbs"],
  ["We ___ an unexpected blue cave during our walk.", "came across", ["came across", "checked out", "looked up to", "came from"], "Phrasal verbs"],
  ["The painting once belonged ___ a private collector.", "to", ["for", "at", "to", "from"], "Phrases with prepositions"],
  ["The visitors were deeply moved ___ the artist’s story.", "by", ["with", "by", "at", "for"], "Phrases with prepositions"],
  ["She has always been devoted ___ her creative work.", "to", ["to", "in", "from", "on"], "Phrases with prepositions"],
  ["The installation consists ___ hundreds of coloured bottles.", "of", ["from", "with", "of", "at"], "Phrases with prepositions"],
  ["The artist is currently working ___ a series about storms.", "on", ["for", "on", "to", "in"], "Phrases with prepositions"],
  ["A new room was added ___ the gallery last year.", "to", ["at", "for", "to", "by"], "Phrases with prepositions"],
  ["The exhibition appeals ___ visitors of all ages.", "to", ["with", "to", "from", "on"], "Phrases with prepositions"],
  ["She succeeded ___ recreating the exact shade of blue.", "in", ["at", "on", "in", "for"], "Phrases with prepositions"],
  ["Leo usually ___ the weather forecast before leaving home.", "checks", ["checks", "is checking", "has checked", "check"], "Present simple"],
  ["The northern lights often ___ without warning.", "appear", ["appears", "are appearing", "appear", "have appeared"], "Present simple"],
  ["I ___ this nature programme every Thursday.", "watch", ["am watching", "watch", "have watched", "watched"], "Present simple"],
  ["Mina ___ a podcast about rare weather events right now.", "is recording", ["records", "has recorded", "is recording", "record"], "Present continuous"],
  ["Look! The clouds ___ a perfect circle.", "are forming", ["form", "have formed", "are forming", "formed"], "Present continuous"],
  ["We ___ at a guesthouse near the coast this week.", "are staying", ["stay", "have stayed", "are staying", "stayed"], "Present continuous"],
  ["I ___ that blue is a calming colour.", "believe", ["am believing", "believe", "have believed", "believed"], "State verbs"],
  ["This camera ___ to my sister.", "belongs", ["is belonging", "belongs", "has belonged", "belong"], "State verbs"],
  ["The guide ___ what caused the glowing water.", "knows", ["is knowing", "knows", "has known", "know"], "State verbs"],
  ["Researchers ___ the unusual rocks for several months.", "have studied", ["study", "are studying", "have studied", "studied"], "Present perfect"],
  ["I ___ that documentary three times.", "have seen", ["see", "am seeing", "have seen", "saw"], "Present perfect"],
  ["The photographer ___ from five different countries so far.", "has reported", ["reports", "is reporting", "has reported", "reported"], "Present perfect"],
  ["We ___ for the storm to clear since dawn.", "have been waiting", ["wait", "are waiting", "have been waiting", "waited"], "Present perfect continuous"],
  ["She ___ night skies for over a decade.", "has been photographing", ["photographs", "is photographing", "has been photographing", "photographed"], "Present perfect continuous"],
  ["How long ___ you ___ this science channel?", "have / been following", ["do / follow", "are / following", "have / been following", "did / follow"], "Present perfect continuous"],
  ["The sea ___ bright blue whenever these tiny organisms gather.", "turns", ["turns", "is turning", "has turned", "turn"], "Present simple"],
  ["Why ___ you ___ at the sky?", "are / looking", ["do / look", "are / looking", "have / looked", "did / look"], "Present continuous"],
  ["A fire rainbow is a rare optical ___.", "phenomenon", ["forecast", "phenomenon", "climate", "season"], "Unusual natural phenomena"],
  ["The sudden flash of light was visible on the ___.", "horizon", ["surface", "horizon", "shadow", "valley"], "Unusual natural phenomena"],
  ["The rocks seem to move because of a natural optical ___.", "illusion", ["opinion", "illusion", "attitude", "routine"], "Unusual natural phenomena"],
  ["The photographer waited for the perfect weather ___.", "conditions", ["behaviour", "conditions", "habits", "directions"], "Unusual natural phenomena"],
  ["A powerful storm can produce an extraordinary ___.", "display", ["display", "schedule", "habit", "portrait"], "Unusual natural phenomena"],
  ["The scientist offered a simple ___ for the coloured snow.", "explanation", ["preference", "explanation", "association", "impression"], "Unusual natural phenomena"],
  ["The event was so rare that local people had never ___ it before.", "witnessed", ["invented", "witnessed", "represented", "respected"], "Unusual natural phenomena"],
  ["My morning ___ includes checking the news and making coffee.", "routine", ["attitude", "routine", "association", "preference"], "Routines and media"],
  ["The presenter gave a balanced ___ of the new documentary.", "opinion", ["opinion", "condition", "phenomenon", "horizon"], "Routines and media"],
  ["Social media has a strong ___ on how quickly stories spread.", "influence", ["influence", "routine", "surface", "forecast"], "Routines and media"],
  ["I would ___ travelling by train because it is more relaxing.", "prefer", ["prefer", "belong", "consist", "succeed"], "Travel preferences"],
  ["Our ideal trip would ___ visits to galleries and nature reserves.", "include", ["devote", "include", "appeal", "represent"], "Travel preferences"],
  ["The mural uses several ___ of blue to create depth.", "shades", ["shades", "conditions", "routines", "forecasts"], "Colour and art"],
  ["The artist’s home is now open ___ the public.", "to", ["for", "at", "to", "with"], "Art and places"],
  ["Our guide suggested ___ the coastal gallery before lunch.", "visiting", ["visit", "to visiting", "visiting", "visited"], "Travel and art"],
]);

const unit2Questions = makeQuestions("unit2", [
  ["Colour often plays an important ___ in film design.", "role", ["role", "habit", "depth", "reaction"], "Verb + noun collocations"],
  ["Some directors have a ___ to use warm colours in happy scenes.", "tendency", ["conclusion", "tendency", "message", "focus"], "Verb + noun collocations"],
  ["Soft lighting can add ___ to a simple scene.", "depth", ["danger", "depth", "notice", "answer"], "Verb + noun collocations"],
  ["The actor quickly became the ___ of media attention.", "focus", ["role", "impression", "focus", "reaction"], "Verb + noun collocations"],
  ["The reviewers came to the ___ that the ending was too long.", "conclusion", ["conclusion", "tendency", "message", "target"], "Verb + noun collocations"],
  ["The final shot conveys a powerful ___.", "message", ["habit", "message", "depth", "danger"], "Verb + noun collocations"],
  ["Her confident performance gave the ___ that she was experienced.", "impression", ["reaction", "impression", "conclusion", "focus"], "Verb + noun collocations"],
  ["The hero must face ___ before reaching safety.", "danger", ["notice", "danger", "role", "impact"], "Verb + noun collocations"],
  ["The joke provoked a positive ___ from the audience.", "reaction", ["reaction", "tendency", "message", "depth"], "Verb + noun collocations"],
  ["The orange background creates a strong visual ___.", "impact", ["habit", "impact", "answer", "conclusion"], "Verb + noun collocations"],
  ["The advert was completely ___ because the claims were false.", "dishonest", ["unhonest", "dishonest", "inhonest", "irhonest"], "Negative prefixes"],
  ["That brand of sun cream is quite ___.", "inexpensive", ["unexpensive", "inexpensive", "disexpensive", "irexpensive"], "Negative prefixes"],
  ["The instructions were ___, so I asked for help.", "unclear", ["disclear", "unclear", "inclear", "irclear"], "Negative prefixes"],
  ["The colour looked ___ under the studio lights.", "unnatural", ["innatural", "disnatural", "unnatural", "irnatural"], "Negative prefixes"],
  ["It is ___ to enter the cinema without a ticket.", "illegal", ["unlegal", "illegal", "dislegal", "inlegal"], "Negative prefixes"],
  ["The old screen made the image almost ___.", "invisible", ["unvisible", "invisible", "disvisible", "irvisible"], "Negative prefixes"],
  ["His account of the event was highly ___.", "improbable", ["unprobable", "improbable", "disprobable", "irprobable"], "Negative prefixes"],
  ["The actor became ___ when the interview began late.", "impatient", ["unpatient", "impatient", "dispatient", "inpatient"], "Negative prefixes"],
  ["The two versions are ___ because they use different endings.", "inconsistent", ["unconsistent", "inconsistent", "disconsistent", "irconsistent"], "Negative prefixes"],
  ["The fake tan left an ___ covering on her skin.", "irregular", ["unregular", "irregular", "disregular", "inregular"], "Negative prefixes"],
  ["I ___ a documentary when the power went out.", "was watching", ["watched", "was watching", "had watched", "used to watch"], "Past continuous"],
  ["We ___ the film at a small cinema last Friday.", "saw", ["saw", "were seeing", "had seen", "see"], "Past simple"],
  ["While the director ___, the actors waited quietly.", "was speaking", ["spoke", "was speaking", "had spoken", "used to speak"], "Past continuous"],
  ["By the time we arrived, the film ___.", "had started", ["started", "was starting", "had started", "starts"], "Past perfect"],
  ["She was nervous because she ___ in front of a camera before.", "had never acted", ["never acted", "was never acting", "had never acted", "never acts"], "Past perfect"],
  ["The audience cheered after the hero ___ the final challenge.", "had completed", ["completed", "was completing", "had completed", "completes"], "Past perfect"],
  ["I ___ cartoons every morning when I was little.", "used to watch", ["was watching", "used to watch", "had watched", "watch"], "Used to"],
  ["My grandfather ___ tell us stories about old cinemas.", "would", ["used", "would", "was", "had"], "Would for past habits"],
  ["There ___ be a video shop on this corner.", "used to", ["would", "used to", "was", "had"], "Used to"],
  ["We ___ dinner when the phone rang.", "were having", ["had", "were having", "had had", "used to have"], "Past continuous"],
  ["The actor ___ the script before rehearsals began.", "had read", ["read", "was reading", "had read", "reads"], "Past perfect"],
  ["I ___ that orange symbol many times as a child.", "saw", ["saw", "was seeing", "had seen", "see"], "Past simple"],
  ["At first, Maya ___ the story was true.", "believed", ["believed", "was believing", "had believe", "believes"], "Past simple"],
  ["When the lights came on, everyone ___ toward the stage.", "was looking", ["looked", "was looking", "had looked", "looks"], "Past continuous"],
  ["He ___ in monsters, but he changed his mind years ago.", "used to believe", ["was believing", "used to believe", "had believed", "believes"], "Used to"],
  ["The film’s ___ made the historical setting believable.", "costumes", ["costumes", "tans", "habits", "prefaces"], "Film vocabulary"],
  ["The camera work gave the scene a frightening ___.", "atmosphere", ["atmosphere", "conclusion", "covering", "tendency"], "Film vocabulary"],
  ["The final scene completely changed my ___ of the main character.", "impression", ["impression", "habit", "depth", "notice"], "Film vocabulary"],
  ["The children once believed that toys came ___ at night.", "alive", ["awake", "alive", "open", "true"], "Childhood beliefs"],
  ["As a child, I was ___ that the moon followed our car.", "convinced", ["convinced", "concluded", "covered", "focused"], "Childhood beliefs"],
  ["The story reminded her ___ a belief she had as a child.", "of", ["from", "of", "for", "at"], "Past beliefs"],
  ["The speaker admitted that the childhood story was ___.", "made-up", ["made-up", "grown-up", "warm-up", "set-up"], "Childhood beliefs"],
  ["A good fake tan should give an even ___.", "covering", ["covering", "patience", "role", "habit"], "Fake tanning"],
  ["Some tanning products are unsuitable for ___ skin.", "sensitive", ["sensible", "sensitive", "sensiblely", "sensitivity"], "Fake tanning"],
  ["Pumpkin spice is strongly ___ with autumn.", "associated", ["associated", "concluded", "devoted", "consisted"], "Pumpkin spice"],
  ["The drink contains a mixture of several ___.", "spices", ["spices", "shades", "roles", "tans"], "Pumpkin spice"],
  ["She chose a handmade necklace as a thoughtful ___.", "gift", ["belief", "gift", "reaction", "covering"], "Great gifts"],
  ["The present was beautifully ___.", "wrapped", ["wrapped", "acted", "covered", "focused"], "Great gifts"],
  ["The review was ___ because it mentioned both strengths and weaknesses.", "balanced", ["balanced", "dishonest", "impatient", "irregular"], "Reviews"],
  ["The opening scene caught the audience’s ___.", "attention", ["attention", "tendency", "habit", "danger"], "Film vocabulary"],
]);

const unit3Questions = makeQuestions("unit3", [
  ["This discovery could ___ a real difference to local farmers.", "make", ["make", "do", "take", "have"], "Make and do"],
  ["We can’t ___ without clean water.", "do", ["make", "do", "get", "take"], "Make and do"],
  ["Too much salt can ___ harm to your health.", "do", ["make", "do", "give", "take"], "Make and do"],
  ["The two companies decided to ___ a deal.", "make", ["do", "make", "set", "hold"], "Make and do"],
  ["The artist had to ___ do with the materials available.", "make", ["get", "make", "do", "take"], "Make and do"],
  ["Every label was written ___ hand.", "by", ["with", "at", "by", "on"], "Make and do"],
  ["The new process could ___ a huge profit.", "make", ["do", "make", "bring", "set"], "Make and do"],
  ["Please ___ your best to arrive on time.", "do", ["make", "do", "have", "give"], "Make and do"],
  ["The medicine should ___ you good.", "do", ["make", "do", "take", "get"], "Make and do"],
  ["We need to ___ a decision before Friday.", "make", ["do", "make", "put", "hold"], "Make and do"],
  ["The bright scarf really ___ in the black-and-white photo.", "stands out", ["pays off", "stands out", "figures out", "lives up to"], "Phrasal verbs"],
  ["The photographer carefully ___ every detail before the shoot.", "thought through", ["made up for", "thought through", "messed up", "got away with"], "Phrasal verbs"],
  ["It took me an hour to ___ how the camera worked.", "figure out", ["stand out", "figure out", "pay off", "live up to"], "Phrasal verbs"],
  ["All that practice finally ___ when she won the competition.", "paid off", ["stood out", "paid off", "made up", "got through"], "Phrasal verbs"],
  ["The final image didn’t ___ our expectations.", "live up to", ["get through", "live up to", "figure out", "mess up"], "Phrasal verbs"],
  ["I accidentally ___ the first set of photos.", "messed up", ["paid off", "messed up", "stood out", "thought through"], "Phrasal verbs"],
  ["Extra editing can ___ poor lighting.", "make up for", ["get away with", "make up for", "live on", "stand out"], "Phrasal verbs"],
  ["She managed to ___ the long editing session without a break.", "get through", ["get through", "figure out", "pay off", "mess up"], "Phrasal verbs"],
  ["The photographer couldn’t ___ using someone else’s image.", "get away with", ["stand out", "get away with", "make up for", "live up to"], "Phrasal verbs"],
  ["Please ___ the composition before you press the button.", "think through", ["think through", "pay off", "mess up", "stand out"], "Phrasal verbs"],
  ["The train ___ at 8:15 tomorrow morning.", "leaves", ["will leave", "is leaving", "leaves", "is going to leave"], "Future forms"],
  ["We ___ the photography exhibition this weekend.", "are visiting", ["visit", "are visiting", "will visit", "have visited"], "Future arrangements"],
  ["Look at those clouds! It ___.", "is going to snow", ["snows", "is going to snow", "will snow", "is snowing every day"], "Going to"],
  ["I think the expedition ___ difficult but rewarding.", "will be", ["is being", "will be", "is going be", "has been"], "Predictions"],
  ["By next Friday, we ___ all the photos.", "will have edited", ["will edit", "are editing", "will have edited", "edit"], "Future perfect"],
  ["This time tomorrow, they ___ across the salt flats.", "will be travelling", ["travel", "will travel", "will be travelling", "have travelled"], "Future continuous"],
  ["We ___ at the station at six; the tickets are booked.", "are meeting", ["meet", "are meeting", "will have met", "met"], "Future arrangements"],
  ["Perhaps she ___ us with the party decorations.", "will help", ["helps", "will help", "is helping every day", "helped"], "Future possibility"],
  ["The lecture is about ___ at nine.", "to start", ["start", "to start", "starting yesterday", "started"], "Be about to"],
  ["They ___ a new camera next month; they’ve already saved enough.", "are going to buy", ["buy", "are going to buy", "will have bought yesterday", "bought"], "Going to"],
  ["By 2030, the museum ___ its digital collection.", "will have expanded", ["expands", "will expand", "will have expanded", "is expanding now"], "Future perfect"],
  ["At noon, I ___ the guests around the gallery.", "will be showing", ["show", "will be showing", "will have shown", "showed"], "Future continuous"],
  ["Don’t call at eight; we ___ the surprise party.", "will be setting up", ["set up", "will be setting up", "will have set up yesterday", "set"], "Future continuous"],
  ["I promise I ___ anyone your secret.", "won’t tell", ["don’t tell", "won’t tell", "am not telling yesterday", "haven’t told"], "Future decisions"],
  ["By the time you arrive, the guests ___.", "will have eaten", ["eat", "will eat", "will have eaten", "are eating yesterday"], "Future perfect"],
  ["Salt was once a highly valuable ___.", "commodity", ["commodity", "portrait", "festival", "forecast"], "Salt: history and uses"],
  ["A small amount of salt can improve the ___ of a dish.", "flavour", ["flavour", "shade", "attitude", "horizon"], "Salt: history and uses"],
  ["The witness was praised for her ___.", "honesty", ["honesty", "whiteness", "saltness", "future"], "Honesty and white lies"],
  ["He told a small white lie to avoid ___ her feelings.", "hurting", ["hurt", "hurting", "to hurted", "hurts"], "Honesty and white lies"],
  ["The editor restored colour to the old ___.", "photograph", ["photograph", "commodity", "expedition", "decision"], "Black-and-white photography"],
  ["Careful lighting can make a portrait more ___.", "striking", ["striking", "salty", "honest", "future"], "Photography"],
  ["The climbers wanted a ___ experience, so they chose ice climbing.", "thrilling", ["thrilling", "ordinary", "handmade", "balanced"], "Thrill-seeking sports"],
  ["Safety equipment is ___ for adventure sports.", "essential", ["essential", "optional", "dishonest", "colourless"], "Thrill-seeking sports"],
  ["Why don’t we ___ the party at my house?", "hold", ["hold", "do", "take", "bring"], "Party suggestions"],
  ["We could ___ everyone a message with the details.", "send", ["send", "make", "hold", "do"], "Party suggestions"],
  ["A thoughtful host should consider every guest’s dietary ___.", "needs", ["needs", "shades", "portraits", "forecasts"], "Party planning"],
  ["The handmade frame will make a ___ gift.", "memorable", ["memorable", "salty", "future", "ordinary"], "Gifts"],
  ["The photographer asked us to remain completely ___.", "still", ["still", "honest", "future", "salty"], "Photography"],
  ["The salt sculpture will slowly ___ if it gets wet.", "dissolve", ["dissolve", "focus", "wrap", "predict"], "Salt: uses"],
  ["The invitation says the celebration will ___ place outdoors.", "take", ["make", "take", "do", "have"], "Party planning"],
]);

const unit4Questions = makeQuestions("unit4", [
  ["Let the soup ___ before you taste it.", "cool down", ["cool down", "eat up", "go off", "heat up"], "Food phrasal verbs"],
  ["The doctor advised him to ___ sugary snacks.", "cut down on", ["eat out", "cut down on", "go for", "live on"], "Food phrasal verbs"],
  ["We usually ___ on Fridays instead of cooking.", "eat out", ["eat up", "eat out", "go off", "heat up"], "Food phrasal verbs"],
  ["Please ___ your vegetables before they get cold.", "eat up", ["cool down", "eat up", "go for", "live on"], "Food phrasal verbs"],
  ["The milk will ___ if you leave it in the sun.", "go off", ["go for", "go off", "heat up", "eat out"], "Food phrasal verbs"],
  ["I think I’ll ___ the fruit salad.", "go for", ["live on", "go for", "cut down on", "cool down"], "Food phrasal verbs"],
  ["Could you ___ the sauce before serving it?", "heat up", ["eat up", "heat up", "go off", "eat out"], "Food phrasal verbs"],
  ["You can’t ___ fast food and expect to feel healthy.", "live on", ["go for", "live on", "cool down", "eat up"], "Food phrasal verbs"],
  ["The tea is too hot, so wait for it to ___.", "cool down", ["go off", "cool down", "eat out", "live on"], "Food phrasal verbs"],
  ["We’re trying to ___ the amount of sugar we eat.", "cut down on", ["heat up", "cut down on", "go for", "eat up"], "Food phrasal verbs"],
  ["The team finally reached an ___ after a long discussion.", "agreement", ["agreeance", "agreement", "agreeity", "agreation"], "Noun suffixes"],
  ["Her natural ___ made everyone feel welcome.", "hospitality", ["hospitance", "hospitality", "hospitalment", "hospitation"], "Noun suffixes"],
  ["The city’s rapid ___ created many new jobs.", "development", ["developity", "development", "developance", "develoption"], "Noun suffixes"],
  ["The museum’s main ___ is its unusual architecture.", "attraction", ["attractment", "attraction", "attractity", "attractance"], "Noun suffixes"],
  ["There has been a significant ___ in public transport.", "improvement", ["improvement", "improvity", "improvence", "improvation"], "Noun suffixes"],
  ["The guide gave a clear ___ for the city’s nickname.", "explanation", ["explainment", "explanation", "explainity", "explainance"], "Noun suffixes"],
  ["The artist is known for her ___.", "originality", ["originalment", "originality", "originaltion", "originalance"], "Noun suffixes"],
  ["The project places great ___ on accessible design.", "importance", ["importity", "importance", "importment", "importtion"], "Noun suffixes"],
  ["The new rule caused considerable ___.", "inconvenience", ["inconveniently", "inconvenience", "inconveniency", "inconvenement"], "Noun suffixes"],
  ["Everyone has a ___ to protect the environment.", "responsibility", ["responsibleness", "responsibility", "responsivement", "responsiblation"], "Noun suffixes"],
  ["Nora said that she ___ the festival the previous year.", "had attended", ["attended", "had attended", "would attend tomorrow", "attends"], "Reported speech"],
  ["Leo told me he ___ tired.", "was", ["is", "was", "has", "will"], "Reported speech"],
  ["Mia said, ‘I can help.’ Mia said that she ___ help.", "could", ["can", "could", "will", "may"], "Reported speech"],
  ["The guide explained that the city ___ famous for its pink buildings.", "was", ["is yesterday", "was", "has being", "will been"], "Reported speech"],
  ["‘I’ll call you tomorrow,’ Ana said. Ana said she ___ call me the next day.", "would", ["will", "would", "can", "must"], "Reported speech"],
  ["Ben asked me where I ___.", "lived", ["live", "lived", "will live", "have live"], "Reported questions"],
  ["The teacher asked us ___ we had enjoyed the exhibition.", "whether", ["that", "whether", "what", "because"], "Reported questions"],
  ["Maya asked, ‘What time does it start?’ Maya asked what time it ___.", "started", ["starts", "started", "has start", "will starting"], "Reported questions"],
  ["Dad told me ___ the hot pan.", "not to touch", ["don’t touch", "not to touch", "not touching", "to not touched"], "Reported commands"],
  ["The organiser asked us ___ our tickets.", "to show", ["show", "to show", "showing", "showed"], "Reported requests"],
  ["‘Please arrive early,’ she said. She asked us ___ early.", "to arrive", ["arrive", "to arrive", "arriving", "arrived"], "Reported requests"],
  ["He said that he ___ never seen pink snow before.", "had", ["has", "had", "was", "would"], "Reported speech"],
  ["The reporter asked the artist ___ inspired her.", "what", ["that", "what", "if", "wherever"], "Reported questions"],
  ["Lena said she ___ working on a new sculpture then.", "was", ["is", "was", "has", "will"], "Reported speech"],
  ["The chef warned us ___ too much sugar.", "not to add", ["don’t add", "not to add", "not adding", "to not added"], "Reported commands"],
  ["Candyfloss is made by ___ sugar at high speed.", "spinning", ["spinning", "reporting", "cooling", "painting"], "Candyfloss"],
  ["The sweet has a light, ___ texture.", "fluffy", ["fluffy", "solid", "bitter", "rough"], "Candyfloss"],
  ["He felt deeply ___ when he forgot everyone’s names.", "embarrassed", ["embarrassing", "embarrassed", "embarrassment", "embarrass"], "Embarrassment"],
  ["The situation was so ___ that nobody knew what to say.", "awkward", ["optimistic", "awkward", "fluffy", "historic"], "Embarrassment"],
  ["The old city is famous for its ___ walls.", "pink", ["reported", "pink", "fluffy", "spun"], "Pink cities"],
  ["Tourism has brought economic ___ to the region.", "development", ["development", "embarrassment", "spinning", "reaction"], "Pink cities"],
  ["Colour can influence how people ___ a product.", "perceive", ["perceive", "report", "spin", "embarrass"], "Colour and gender"],
  ["The campaign challenged traditional gender ___.", "stereotypes", ["stereotypes", "textures", "suffixes", "questions"], "Colour and gender"],
  ["Despite the delay, the group remained ___.", "optimistic", ["optimistic", "embarrassed", "fluffy", "reported"], "Optimism"],
  ["She has a positive ___ toward difficult situations.", "attitude", ["attitude", "texture", "suffix", "command"], "Optimism"],
  ["The review praised the festival’s lively ___.", "atmosphere", ["atmosphere", "embarrassment", "agreement", "question"], "Festival reviews"],
  ["The reviewer thought the music was too ___.", "repetitive", ["repetitive", "optimistic", "fluffy", "historic"], "Festival reviews"],
  ["The event is highly ___ with local families.", "popular", ["popular", "reported", "spun", "awkwardly"], "Festival reviews"],
  ["The city council plans to ___ the historic market.", "conserve", ["conserve", "embarrass", "spin", "report"], "Pink cities"],
  ["The speaker’s final comment left a strong ___.", "impression", ["impression", "agreement", "hospitality", "originality"], "Noun formation"],
]);

const unit5Questions = makeQuestions("unit5", [
  ["The material absorbs a high ___ of visible light.", "percentage", ["percentage", "knowledge", "admiration", "future"], "Adjective + noun collocations"],
  ["It is common ___ that dark colours absorb heat.", "knowledge", ["knowledge", "improvement", "row", "right"], "Adjective + noun collocations"],
  ["The inventor earned great ___ from other scientists.", "admiration", ["admiration", "percentage", "criticism", "idea"], "Adjective + noun collocations"],
  ["The second design was a vast ___ on the first.", "improvement", ["improvement", "knowledge", "future", "row"], "Adjective + noun collocations"],
  ["In the early ___, the product was used only in laboratories.", "days", ["days", "rights", "ideas", "percentages"], "Adjective + noun collocations"],
  ["I only have a rough ___ of how the technology works.", "idea", ["idea", "future", "row", "knowledge"], "Adjective + noun collocations"],
  ["The company believes the invention has a bright ___.", "future", ["future", "criticism", "percentage", "days"], "Adjective + noun collocations"],
  ["The artist bought the exclusive ___ to use the coating.", "rights", ["rights", "knowledge", "rows", "improvements"], "Adjective + noun collocations"],
  ["The decision caused a bitter ___ between the partners.", "row", ["row", "future", "admiration", "idea"], "Adjective + noun collocations"],
  ["The project received harsh ___ from environmental groups.", "criticism", ["criticism", "percentage", "knowledge", "right"], "Adjective + noun collocations"],
  ["Many customers tend ___ coffee without sugar.", "to drink", ["drink", "to drink", "drinking", "drank"], "Verb patterns"],
  ["I really feel like ___ a hot chocolate.", "having", ["have", "to have", "having", "had"], "Verb patterns"],
  ["This recipe involves ___ the beans slowly.", "roasting", ["roast", "to roast", "roasting", "roasted"], "Verb patterns"],
  ["The café requires customers ___ at the counter.", "to order", ["order", "to order", "ordering", "ordered"], "Verb patterns"],
  ["The guide recommends ___ the local coffee.", "trying", ["try", "to trying", "trying", "tried"], "Verb patterns"],
  ["We attempted ___ our own beans at home.", "to roast", ["roast", "to roast", "roasting only", "roasted"], "Verb patterns"],
  ["She admitted ___ the wrong type of coffee.", "buying", ["buy", "to buy", "buying", "bought"], "Verb patterns"],
  ["The waiter offered ___ us another cup.", "to bring", ["bring", "to bring", "bringing", "brought"], "Verb patterns"],
  ["They avoided ___ disposable cups.", "using", ["use", "to use", "using", "used"], "Verb patterns"],
  ["The owner promised ___ more plant-based options.", "to provide", ["provide", "to provide", "providing", "provided"], "Verb patterns"],
  ["If the sky is clear tonight, we ___ the stars.", "will see", ["see yesterday", "will see", "would see", "had seen"], "First conditional"],
  ["If I had more time, I ___ a fashion course.", "would take", ["will take", "would take", "took", "had taken"], "Second conditional"],
  ["If they had checked the label, they ___ the mistake.", "would have noticed", ["will notice", "would notice", "would have noticed", "noticed"], "Third conditional"],
  ["If water reaches 100°C, it ___.", "boils", ["will boil", "boils", "would boil", "boiled"], "Zero conditional"],
  ["Unless the price drops, I ___ the jacket.", "won’t buy", ["don’t buy yesterday", "won’t buy", "wouldn’t bought", "hadn’t bought"], "First conditional"],
  ["We’ll sit outside provided that it ___ warm.", "stays", ["will stay", "stays", "would stay", "stayed yesterday"], "Conditional forms"],
  ["If I were you, I ___ the receipt.", "would keep", ["will keep", "would keep", "kept", "had kept"], "Second conditional"],
  ["Had the shop advertised earlier, more people ___.", "would have come", ["will come", "would come", "would have come", "came"], "Third conditional"],
  ["If factories reduced emissions, the air ___ cleaner.", "would become", ["will become", "would become", "became", "had become"], "Second conditional"],
  ["You can borrow my coat as long as you ___ it tomorrow.", "return", ["will return", "return", "would return", "returned yesterday"], "Conditional forms"],
  ["If the alarm goes off, everyone ___ the building.", "must leave", ["must leave", "would left", "had left", "leaves yesterday"], "Zero conditional"],
  ["Even if the sale continues, I ___ anything else.", "won’t buy", ["don’t buy yesterday", "won’t buy", "wouldn’t bought", "hadn’t bought"], "Conditional forms"],
  ["If she hadn’t missed the bus, she ___ late.", "wouldn’t have been", ["won’t be", "wouldn’t be", "wouldn’t have been", "wasn’t"], "Third conditional"],
  ["Suppose you ___ a completely black room; how would you feel?", "entered", ["enter tomorrow", "entered", "had enter", "will entered"], "Second conditional"],
  ["If people buy less, shops ___ fewer products.", "will order", ["order yesterday", "will order", "would ordered", "had ordered"], "First conditional"],
  ["Vantablack can ___ almost all visible light.", "absorb", ["absorb", "reflect", "print", "brew"], "Vantablack"],
  ["Objects covered in the material appear almost ___.", "flat", ["flat", "transparent", "colourful", "traditional"], "Vantablack"],
  ["The designer used texture to make the black outfit more ___.", "striking", ["striking", "conditional", "roasted", "polluted"], "Fashion"],
  ["Fast fashion can create large amounts of ___.", "waste", ["waste", "admiration", "knowledge", "night"], "Fashion"],
  ["Coffee beans develop flavour during the ___ process.", "roasting", ["roasting", "absorbing", "reflecting", "printing"], "Coffee culture"],
  ["In some cultures, coffee is served as a sign of ___.", "hospitality", ["hospitality", "criticism", "pollution", "condition"], "Coffee culture"],
  ["Black Friday encourages shoppers to look for ___.", "bargains", ["bargains", "emissions", "shadows", "beans"], "Black Friday"],
  ["An impulse purchase is something bought without much ___.", "thought", ["thought", "light", "waste", "night"], "Black Friday"],
  ["Factories must reduce harmful ___.", "emissions", ["emissions", "bargains", "rights", "beans"], "Air pollution"],
  ["Public transport can help improve air ___.", "quality", ["quality", "percentage", "fashion", "knowledge"], "Air pollution"],
  ["The city is much quieter at ___.", "night", ["night", "roasting", "future", "sale"], "Night"],
  ["Reflective clothing makes cyclists more ___ after dark.", "visible", ["visible", "conditional", "polluted", "exclusive"], "Night"],
  ["The advert persuaded customers ___ the limited-edition coat.", "to buy", ["buy", "to buy", "buying", "bought"], "Verb patterns"],
  ["If the material were cheaper, more artists ___ it.", "would use", ["will use", "would use", "used yesterday", "had used"], "Second conditional"],
  ["If commuters shared cars more often, traffic pollution ___.", "would decrease", ["will decrease", "would decrease", "decreased yesterday", "had decreased"], "Second conditional"],
]);

const unit6Questions = makeQuestions("unit6", [
  ["The sauce was so spicy that it felt like a ___ in my mouth.", "firework", ["firework", "lifetime", "teaspoon", "homemade"], "Compound words"],
  ["This bread is completely ___.", "homemade", ["homemade", "widespread", "never-ending", "underwater"], "Compound words"],
  ["The burning sensation seemed ___.", "never-ending", ["well-known", "never-ending", "teaspoon", "firework"], "Compound words"],
  ["Add one ___ of chilli powder.", "teaspoon", ["lifetime", "teaspoon", "firework", "homemade"], "Compound words"],
  ["The recipe is ___ across the region.", "well-known", ["underwater", "well-known", "never-ending", "lifetime"], "Compound words"],
  ["Chilli peppers are now ___ around the world.", "widespread", ["homemade", "widespread", "teaspoon", "firework"], "Compound words"],
  ["The chef has spent a ___ developing this sauce.", "lifetime", ["lifetime", "teaspoon", "firework", "underestimate"], "Compound words"],
  ["Never ___ how hot a small chilli can be.", "underestimate", ["underestimate", "homemade", "widespread", "well-known"], "Compound words"],
  ["The charity sale included cakes and other ___ treats.", "home-made", ["home-made", "life-long", "under-time", "wide-made"], "Compound words"],
  ["A ___ supporter follows the team for many years.", "lifelong", ["lifelong", "teaspoon", "firework", "widespreadly"], "Compound words"],
  ["The final match was extremely ___.", "exciting", ["exciteful", "exciting", "excitic", "excitive"], "Adjective suffixes"],
  ["Her speech was both moving and ___.", "inspiring", ["inspireful", "inspiring", "inspiric", "inspirous"], "Adjective suffixes"],
  ["The charity’s work has been highly ___.", "effective", ["effecting", "effectful", "effective", "effectal"], "Adjective suffixes"],
  ["The crowd became ___ when the referee made the decision.", "aggressive", ["aggressful", "aggressive", "aggressic", "agressing"], "Adjective suffixes"],
  ["The old tradition is still ___ in the town.", "symbolic", ["symboling", "symbolful", "symbolic", "symbolive"], "Adjective suffixes"],
  ["The team gave an ___ performance.", "impressive", ["impressing", "impressful", "impressive", "impressal"], "Adjective suffixes"],
  ["The documentary was surprisingly ___.", "dramatic", ["dramaful", "dramatic", "dramaive", "dramaing"], "Adjective suffixes"],
  ["His comments were deeply ___.", "thoughtful", ["thoughting", "thoughtful", "thoughtic", "thoughtive"], "Adjective suffixes"],
  ["The fans were very ___ about the injured player.", "sympathetic", ["sympathyful", "sympathetic", "sympathyive", "sympathying"], "Adjective suffixes"],
  ["The colour red can appear warm and ___.", "energetic", ["energyful", "energetic", "energyive", "energying"], "Adjective suffixes"],
  ["This sauce is ___ than the one we tried yesterday.", "hotter", ["more hot", "hotter", "hottest", "as hot"], "Comparatives"],
  ["The red dress is ___ expensive than the black one.", "less", ["least", "less", "fewer", "as"], "Comparatives"],
  ["Today’s event is far ___ organised than last year’s.", "better", ["good", "better", "best", "more good"], "Comparatives"],
  ["The queue was not as long ___ we expected.", "as", ["than", "as", "like", "from"], "Comparatives"],
  ["The more you practise, the ___ you become.", "more confident", ["most confident", "more confident", "confidentest", "as confident"], "Comparatives"],
  ["This year’s campaign is by far the ___ successful.", "most", ["more", "most", "much", "as"], "Superlatives"],
  ["There are ___ volunteers this year than last year.", "fewer", ["less", "fewer", "fewest", "little"], "Comparatives"],
  ["The new stadium is twice as large ___ the old one.", "as", ["than", "as", "like", "from"], "Comparatives"],
  ["Her second speech was slightly ___ than her first.", "shorter", ["short", "shorter", "shortest", "more shortly"], "Comparatives"],
  ["The match was much ___ exciting than the warm-up game.", "more", ["most", "more", "many", "as"], "Comparatives"],
  ["No other runner was ___ fast as Mia.", "as", ["than", "as", "more", "most"], "Comparatives"],
  ["The red carpet looked ___ glamorous in daylight.", "less", ["fewer", "less", "least", "little"], "Comparatives"],
  ["This is the ___ chilli I have ever tasted.", "hottest", ["hotter", "hottest", "most hot", "more hot"], "Superlatives"],
  ["The sooner we begin, the ___ we will finish.", "earlier", ["early", "earlier", "earliest", "more early"], "Comparatives"],
  ["My seat was nowhere near as comfortable ___ yours.", "as", ["than", "as", "like", "from"], "Comparatives"],
  ["The chemical that makes chillies hot is called ___.", "capsaicin", ["capsaicin", "sympathy", "firework", "carpet"], "Red chillies"],
  ["A tiny amount can produce a strong burning ___.", "sensation", ["sensation", "tradition", "collection", "donation"], "Red chillies"],
  ["Graduation day was a red-letter ___.", "day", ["day", "carpet", "chilli", "sale"], "Red-letter days"],
  ["The award ceremony was an important ___ in her career.", "occasion", ["occasion", "sauce", "donation", "symbol"], "Red-letter days"],
  ["Celebrities posed for photographers on the red ___.", "carpet", ["carpet", "pepper", "letter", "sale"], "Red carpet"],
  ["The event attracted a great deal of media ___.", "attention", ["attention", "capsaicin", "spoon", "heat"], "Red carpet"],
  ["When I saw the broken screen, I nearly saw ___.", "red", ["red", "hot", "fire", "carpet"], "Seeing red"],
  ["She was ___ with anger after the unfair decision.", "furious", ["furious", "symbolic", "homemade", "widespread"], "Seeing red"],
  ["The club held a sale to ___ money for new equipment.", "raise", ["rise", "raise", "arise", "raised up"], "Raising money"],
  ["Every ___ will help the community project.", "donation", ["donation", "sensation", "tradition", "occasion"], "Raising money"],
  ["The charity event was more successful ___ expected.", "than", ["as", "than", "like", "from"], "Comparatives"],
  ["The team’s red shirts are instantly ___.", "recognisable", ["recognisable", "aggressive", "never-ending", "homemade"], "Sport and colour"],
  ["The organiser thanked everyone for their ___ support.", "generous", ["generous", "spicy", "symbolic", "dramatic"], "Raising money"],
  ["Compared with last year, the campaign raised ___ money.", "more", ["many", "more", "most", "fewer"], "Comparatives"],
  ["The chilli challenge was easily the ___ popular activity.", "most", ["more", "most", "much", "as"], "Superlatives"],
]);

const unit7Questions = makeQuestions("unit7", [
  ["I’ve recently ___ a new idea for saving water.", "come up with", ["come down with", "come up with", "run out of", "give away"], "Phrasal verbs"],
  ["Several students have ___ a nasty cold.", "come down with", ["come up with", "come down with", "run into", "give off"], "Phrasal verbs"],
  ["If the machine breaks, try to ___ the problem yourself.", "sort out", ["give away", "sort out", "run out of", "come down with"], "Phrasal verbs"],
  ["We’ve ___ clean paper, so please bring some more.", "run out of", ["come up with", "run out of", "give off", "sort out"], "Phrasal verbs"],
  ["These solar lamps ___ enough light for the whole path.", "give off", ["give away", "give off", "run into", "come down with"], "Phrasal verbs"],
  ["The shop plans to ___ reusable bags this weekend.", "give away", ["give off", "give away", "sort out", "run out of"], "Phrasal verbs"],
  ["Engineers sometimes ___ unexpected difficulties.", "run into", ["run into", "give away", "come down with", "give off"], "Phrasal verbs"],
  ["Creative teams often ___ the best solutions.", "come up with", ["run out of", "come up with", "sort out", "give off"], "Phrasal verbs"],
  ["We need to ___ how to reduce the building’s energy use.", "work out", ["work out", "give away", "come down with", "run out of"], "Phrasal verbs"],
  ["The old wallpaper may ___ a harmful chemical smell.", "give off", ["sort out", "give off", "come up with", "run into"], "Phrasal verbs"],
  ["The museum was built ___ for the exhibition.", "specially", ["especially", "specially", "special", "especial"], "Easily confused words"],
  ["The app is ___ useful for people who cycle to work.", "especially", ["specially", "especially", "special", "especial"], "Easily confused words"],
  ["The building is a ___ example of Victorian design.", "classic", ["classical", "classic", "classified", "classically"], "Easily confused words"],
  ["We listened to ___ music during the presentation.", "classical", ["classic", "classical", "classified", "classed"], "Easily confused words"],
  ["It would be ___ to test the device before buying it.", "sensible", ["sensitive", "sensible", "sensational", "sensibly"], "Easily confused words"],
  ["The sensor is highly ___ to changes in temperature.", "sensitive", ["sensible", "sensitive", "sensational", "sensibly"], "Easily confused words"],
  ["Please ___ me to charge the battery tonight.", "remind", ["recall", "remind", "remembered", "recognise"], "Easily confused words"],
  ["I can’t ___ where I first saw that invention.", "recall", ["remind", "recall", "raise", "rise"], "Easily confused words"],
  ["The charity hopes to ___ awareness of plastic waste.", "raise", ["rise", "raise", "arise", "lift up"], "Easily confused words"],
  ["Energy prices may ___ again this winter.", "rise", ["raise", "rise", "lift", "raised"], "Easily confused words"],
  ["The engineer ___ designed the filter won an award.", "who", ["which", "who", "where", "whose"], "Relative clauses"],
  ["The robot ___ cleans the beach runs on solar power.", "which", ["who", "which", "where", "whose"], "Relative clauses"],
  ["This is the laboratory ___ the device was tested.", "where", ["which", "who", "where", "whose"], "Relative clauses"],
  ["The student ___ idea won is only sixteen.", "whose", ["who", "which", "where", "whose"], "Relative clauses"],
  ["The year ___ the park reopened was unusually warm.", "when", ["which", "who", "when", "whose"], "Relative clauses"],
  ["The bottle, ___ is fully recyclable, is made locally.", "which", ["that", "which", "who", "where"], "Non-defining relative clauses"],
  ["My neighbour, ___ works in green technology, gave us advice.", "who", ["that", "who", "which", "where"], "Non-defining relative clauses"],
  ["The product ___ we tested used very little power.", "that", ["who", "that", "where", "whose"], "Relative clauses"],
  ["The company for ___ she works makes electric bikes.", "which", ["who", "which", "where", "whose"], "Relative clauses"],
  ["The scientist to ___ I spoke explained the results.", "whom", ["which", "whom", "where", "whose"], "Relative clauses"],
  ["Solar panels ___ on the roof can reduce electricity bills.", "installed", ["installing", "installed", "which installing", "were install"], "Reduced relative clauses"],
  ["Students living nearby often walk to school. The full form is students ___ nearby.", "who live", ["which live", "who live", "where live", "whose live"], "Reduced relative clauses"],
  ["The park ___ we visited has a community garden.", "that", ["who", "that", "wherever", "whose"], "Relative clauses"],
  ["The inventor, ___ parents were engineers, built her first robot at ten.", "whose", ["who", "which", "where", "whose"], "Non-defining relative clauses"],
  ["The day on ___ the system failed was extremely hot.", "which", ["who", "which", "where", "whose"], "Relative clauses"],
  ["Some Victorian dyes contained dangerous ___.", "chemicals", ["chemicals", "profits", "screens", "clauses"], "Victorian dangers"],
  ["Factory workers were sometimes exposed to ___ substances.", "toxic", ["toxic", "recyclable", "financial", "sensible"], "Victorian dangers"],
  ["A smart thermostat can reduce energy ___.", "consumption", ["consumption", "pollution", "invention", "discussion"], "Green technology"],
  ["The device is powered by a renewable energy ___.", "source", ["source", "clause", "profit", "warning"], "Green technology"],
  ["A sustainable business should consider its environmental ___.", "impact", ["impact", "income", "screen", "dye"], "Business and green products"],
  ["The company made a small ___ in its first year.", "profit", ["profit", "source", "clause", "poison"], "Business and money"],
  ["Customers are willing to pay more for ___ packaging.", "recyclable", ["recyclable", "toxic", "Victorian", "financially"], "Green products"],
  ["The label proves that the wood was responsibly ___.", "sourced", ["sourced", "raised", "recalled", "reminded"], "Green products"],
  ["Urban green spaces can improve people’s ___.", "well-being", ["well-being", "income", "technology", "poison"], "Green spaces"],
  ["Trees provide shade and reduce air ___.", "pollution", ["pollution", "profit", "opportunity", "warning"], "Green spaces"],
  ["The character faced a difficult moral ___.", "dilemma", ["dilemma", "product", "clause", "source"], "Story dilemmas"],
  ["She had to ___ between helping a friend and telling the truth.", "choose", ["choose", "raise", "recall", "source"], "Story dilemmas"],
  ["The invention gives communities an ___ to save water.", "opportunity", ["possibility", "opportunity", "incidence", "accident"], "Easily confused words"],
  ["There is a real ___ that the trial will succeed.", "possibility", ["opportunity", "possibility", "occasion", "incidence"], "Easily confused words"],
  ["The warning sign was designed for people ___ use the old machine.", "who", ["which", "who", "where", "whose"], "Relative clauses"],
]);

const unit8Questions = makeQuestions("unit8", [
  ["Bees are ___ associated with healthy ecosystems.", "closely", ["closely", "completely", "deeply", "widely"], "Adverb + adjective collocations"],
  ["The two species are ___ different in appearance.", "completely", ["closely", "completely", "highly", "fully"], "Adverb + adjective collocations"],
  ["Farmers are ___ concerned about falling bee numbers.", "deeply", ["widely", "fully", "deeply", "closely"], "Adverb + adjective collocations"],
  ["The guide was ___ aware of the risks.", "fully", ["deeply", "fully", "widely", "completely"], "Adverb + adjective collocations"],
  ["This simple method is highly ___.", "effective", ["affected", "effective", "aware", "associated"], "Adverb + adjective collocations"],
  ["It is ___ believed that bees communicate through movement.", "widely", ["fully", "deeply", "widely", "closely"], "Adverb + adjective collocations"],
  ["The class found the talk incredibly ___.", "interesting", ["interested", "interesting", "effective", "aware"], "Adverb + adjective collocations"],
  ["Pollinators are ___ important for food production.", "vitally", ["completely", "vitally", "closely", "fully"], "Adverb + adjective collocations"],
  ["The two traditions are closely ___.", "linked", ["divided", "linked", "affected", "awake"], "Adverb + adjective collocations"],
  ["The harvest was badly ___ by the dry weather.", "affected", ["effective", "affected", "aware", "associated"], "Adverb + adjective collocations"],
  ["The museum is fully ___ to wheelchair users.", "accessible", ["accessent", "accessible", "accessy", "accessant"], "Adjective suffixes"],
  ["She felt ___ about speaking to the large audience.", "confident", ["confidable", "confident", "confidency", "confidey"], "Adjective suffixes"],
  ["Online messages are quick and ___.", "convenient", ["convenable", "convenient", "conveny", "convenant"], "Adjective suffixes"],
  ["The new heating system is energy-___.", "efficient", ["efficiable", "efficient", "efficiency", "efficieny"], "Adjective suffixes"],
  ["The outdoor lesson was both useful and ___.", "enjoyable", ["enjoyent", "enjoyable", "enjoyy", "enjoyant"], "Adjective suffixes"],
  ["The final scene was extremely ___.", "memorable", ["memoryent", "memorable", "memoryy", "memorant"], "Adjective suffixes"],
  ["The actor is instantly ___.", "recognisable", ["recognisent", "recognisable", "recognisy", "recognisant"], "Adjective suffixes"],
  ["Dark clouds made the afternoon look ___.", "stormy", ["storment", "stormable", "stormy", "stormant"], "Adjective suffixes"],
  ["The puzzle was surprisingly ___.", "tricky", ["trickent", "trickable", "tricky", "trickant"], "Adjective suffixes"],
  ["After the long walk, everyone felt ___.", "sleepy", ["sleepent", "sleepable", "sleepy", "sleepant"], "Adjective suffixes"],
  ["Honey ___ by bees.", "is produced", ["produces", "is produced", "produced", "is producing"], "Present passive"],
  ["The first emojis ___ in Japan.", "were created", ["created", "were created", "are creating", "have create"], "Past passive"],
  ["The results ___ next week.", "will be announced", ["will announce", "will be announced", "are announcing yesterday", "announced"], "Future passive"],
  ["The sculpture ___ at the moment.", "is being displayed", ["displays", "is being displayed", "was displayed tomorrow", "has display"], "Present continuous passive"],
  ["The costumes ___ before the show began.", "had been prepared", ["prepared", "had been prepared", "were preparing", "have prepare"], "Past perfect passive"],
  ["A new nature trail ___ near the school.", "has been opened", ["has opened", "has been opened", "is opening yesterday", "opened by"], "Present perfect passive"],
  ["Visitors must ___ protective clothing.", "be given", ["give", "be given", "been giving", "gave"], "Passive with modals"],
  ["The cheese should ___ at room temperature.", "be served", ["serve", "be served", "be serving", "served"], "Passive with modals"],
  ["The message can ___ in several ways.", "be interpreted", ["interpret", "be interpreted", "be interpreting", "interpreted"], "Passive with modals"],
  ["The bees are thought ___ a complex navigation system.", "to use", ["use", "to use", "using", "used"], "Passive reporting structures"],
  ["The sculpture is believed ___ over 200 years old.", "to be", ["be", "to be", "being", "been"], "Passive reporting structures"],
  ["The festival is expected ___ thousands of visitors.", "to attract", ["attract", "to attract", "attracting", "attracted"], "Passive reporting structures"],
  ["It is widely ___ that outdoor exercise improves mood.", "believed", ["believing", "believed", "belief", "believes"], "Impersonal passive"],
  ["The traditional outfit was made ___ local craftspeople.", "by", ["with", "by", "from", "at"], "Passive agent"],
  ["The model was made ___ recycled paper.", "from", ["by", "from", "at", "to"], "Materials in passive descriptions"],
  ["Worker bees collect ___ from flowers.", "nectar", ["nectar", "clutter", "sculpture", "emoji"], "Honey bees"],
  ["Bees play a vital role in ___.", "pollination", ["pollination", "communication", "celebration", "decoration"], "Honey bees"],
  ["Autumn is my favourite ___ because the air is cooler.", "season", ["season", "species", "message", "costume"], "Favourite seasons"],
  ["Spring is often associated ___ new growth.", "with", ["to", "with", "from", "at"], "Favourite seasons"],
  ["An emoji can add emotion to a written ___.", "message", ["message", "nectar", "season", "outfit"], "Emojis and communication"],
  ["Some emojis have different meanings across ___.", "cultures", ["cultures", "sculptures", "species", "seasons"], "Emojis and communication"],
  ["The chef carved the cheese into a detailed ___.", "sculpture", ["sculpture", "pollination", "costume", "message"], "Food sculptures"],
  ["The artwork must be kept cool to prevent it from ___.", "melting", ["melting", "pollinating", "messaging", "cluttering"], "Food sculptures"],
  ["A close friend is someone you can ___.", "trust", ["trust", "carve", "pollinate", "display"], "Friendship"],
  ["Their friendship has lasted for more than a ___.", "decade", ["decade", "species", "season", "sculpture"], "Friendship"],
  ["Traditional clothes can express cultural ___.", "identity", ["identity", "efficiency", "pollination", "clutter"], "Clothes and culture"],
  ["The costume was decorated ___ hand.", "by", ["with", "by", "from", "at"], "Clothes and culture"],
  ["Spending time outdoors can improve mental ___.", "well-being", ["well-being", "costume", "message", "species"], "Time outdoors"],
  ["The walkers were advised to stay on the marked ___.", "path", ["path", "nectar", "outfit", "emoji"], "Time outdoors"],
  ["The park is ___ used by families at weekends.", "widely", ["deeply", "widely", "completely", "closely"], "Adverb + adjective collocations"],
]);

export const QUIZZES = {
  unit1: {
    name: "Unit 1: Blue",
    description: "Present tenses, phrasal verbs, art & unusual phenomena",
    icon: "1",
    questions: unit1Questions,
  },
  unit2: {
    name: "Unit 2: Orange",
    description: "Past tenses, collocations, film & negative prefixes",
    icon: "2",
    questions: unit2Questions,
  },
  unit3: {
    name: "Unit 3: White",
    description: "Future forms, make/do, photography & celebrations",
    icon: "3",
    questions: unit3Questions,
  },
  unit4: {
    name: "Unit 4: Pink",
    description: "Reported speech, food phrasal verbs & noun suffixes",
    icon: "4",
    questions: unit4Questions,
  },
  unit5: {
    name: "Unit 5: Black",
    description: "Conditionals, verb patterns, fashion & the environment",
    icon: "5",
    questions: unit5Questions,
  },
  unit6: {
    name: "Unit 6: Red",
    description: "Comparatives, compounds, adjective suffixes & fundraising",
    icon: "6",
    questions: unit6Questions,
  },
  unit7: {
    name: "Unit 7: Green",
    description: "Relative clauses, green technology & confused words",
    icon: "7",
    questions: unit7Questions,
  },
  unit8: {
    name: "Unit 8: Yellow",
    description: "Passive forms, adjective collocations & communication",
    icon: "8",
    questions: unit8Questions,
  },
};
