export const CHAMULLERO_QUESTIONS = [
  {
    id: 1,
    term: "Bo",
    emoji: "🎬",
    sentence: "Apurate un poco, bo, que vamos a llegar tarde al cine.",
    answer: "Una forma informal de llamar la atención de alguien",
    options: [
      "Una forma informal de llamar la atención de alguien",
      "Una despedida especialmente afectuosa",
      "Una orden para que alguien se quede quieto",
      "Un insulto dirigido a una persona desconocida",
    ],
  },
  {
    id: 2,
    term: "Ta",
    emoji: "🤝",
    sentence: "Nos vemos mañana a las ocho en la plaza y ta, no se hable más.",
    answer: "Listo; el asunto queda acordado o terminado",
    options: [
      "Quizás; todavía falta tomar una decisión",
      "Listo; el asunto queda acordado o terminado",
      "Esperá; hay que revisar el plan nuevamente",
      "Nunca; la propuesta quedó completamente descartada",
    ],
  },
  {
    id: 3,
    term: "Pila",
    emoji: "⏳",
    sentence: "Hacía pila de tiempo que no nos cruzábamos por el barrio.",
    answer: "Mucho o una gran cantidad",
    options: [
      "Un período muy breve",
      "Una cantidad aproximada",
      "Mucho o una gran cantidad",
      "Exactamente la mitad",
    ],
  },
  {
    id: 4,
    term: "Al mango",
    emoji: "🔊",
    sentence: "Venía con la música del auto al mango y no escuchó la bocina.",
    answer: "Al máximo nivel o intensidad",
    options: [
      "Con interrupciones frecuentes",
      "A un nivel apenas audible",
      "Con una calidad bastante mala",
      "Al máximo nivel o intensidad",
    ],
  },
  {
    id: 5,
    term: "Cualquiera",
    emoji: "🤥",
    sentence: "Me dijo que el examen era facilísimo, pero me mandó cualquiera.",
    answer: "Algo falso, absurdo o que no tiene relación con la realidad",
    options: [
      "Algo falso, absurdo o que no tiene relación con la realidad",
      "Una explicación exacta y muy detallada",
      "Una advertencia útil hecha con anticipación",
      "Una respuesta incompleta pero básicamente correcta",
    ],
  },
  {
    id: 6,
    term: "Botija",
    emoji: "⚽",
    sentence: "Ese botija se pasa todo el día jugando a la pelota en la calle.",
    answer: "Un niño o muchacho joven",
    options: [
      "Un vecino de edad avanzada",
      "Un niño o muchacho joven",
      "Un jugador profesional",
      "Un vendedor ambulante",
    ],
  },
  {
    id: 7,
    term: "Gurisa",
    emoji: "🏛️",
    sentence: "La gurisa de la esquina empezó a estudiar arquitectura este año.",
    answer: "Una niña o mujer joven",
    options: [
      "Una profesora universitaria",
      "Una arquitecta con experiencia",
      "Una niña o mujer joven",
      "Una vecina recién llegada",
    ],
  },
  {
    id: 8,
    term: "Ñeri",
    emoji: "🫂",
    sentence: "Quedate tranquilo, ñeri, que yo te guardo el lugar en la fila.",
    answer: "Amigo, compañero o persona cercana",
    options: [
      "Persona con la que existe una rivalidad",
      "Desconocido al que se trata formalmente",
      "Persona encargada de organizar una fila",
      "Amigo, compañero o persona cercana",
    ],
  },
  {
    id: 9,
    term: "Pibe",
    emoji: "💼",
    sentence: "El pibe nuevo de la oficina trabaja rapidísimo.",
    answer: "Un muchacho o joven",
    options: [
      "Un muchacho o joven",
      "El propietario de una empresa",
      "Un trabajador próximo a jubilarse",
      "El cliente más importante de la oficina",
    ],
  },
  {
    id: 10,
    term: "Mina",
    emoji: "🧠",
    sentence: "Es una mina re inteligente y siempre sabe qué decir para calmar las cosas.",
    answer: "Una mujer",
    options: [
      "Una mujer",
      "Una persona que trabaja bajo tierra",
      "Una amiga de la infancia exclusivamente",
      "Una persona que se enoja con facilidad",
    ],
  },
  {
    id: 11,
    term: "Plancha",
    emoji: "🧢",
    sentence: "Antes se vestía medio plancha, pero ahora cambió pila el estilo.",
    answer: "Con un estilo asociado a la subcultura urbana llamada plancha",
    options: [
      "Con ropa formal para una ceremonia",
      "Con un estilo asociado a la subcultura urbana llamada plancha",
      "Con prendas antiguas heredadas de la familia",
      "Con ropa arrugada y sin planchar",
    ],
  },
  {
    id: 12,
    term: "Cheto",
    emoji: "🍽️",
    sentence: "Fueron a cenar a un restaurante re cheto en Punta Carretas.",
    answer: "Elegante, exclusivo o asociado a gente de dinero",
    options: [
      "Económico y con comida casera",
      "Pequeño, escondido y difícil de encontrar",
      "Elegante, exclusivo o asociado a gente de dinero",
      "Ruidoso y frecuentado por estudiantes",
    ],
  },
  {
    id: 13,
    term: "Gil",
    emoji: "💸",
    sentence: "No seas gil, aprovechá que te están ofreciendo un muy buen sueldo.",
    answer: "Tonto, ingenuo o poco avispado",
    options: [
      "Ambicioso y difícil de conformar",
      "Generoso con sus compañeros",
      "Desconfiado ante cualquier propuesta",
      "Tonto, ingenuo o poco avispado",
    ],
  },
  {
    id: 14,
    term: "Nabo",
    emoji: "🧉",
    sentence: "Puse el mate en la mesa sin el termo como un nabo.",
    answer: "Una persona torpe o que cometió una tontería",
    options: [
      "Una persona torpe o que cometió una tontería",
      "Alguien que prepara muy buen mate",
      "Una persona que actúa con mala intención",
      "Alguien excesivamente cuidadoso",
    ],
  },
  {
    id: 15,
    term: "Banana",
    emoji: "🤡",
    sentence: "Siempre hace chistes malos en las reuniones porque le encanta hacerse el banana.",
    answer: "Hacerse el gracioso, presumido o payaso",
    options: [
      "Evitar participar por vergüenza",
      "Hacerse el gracioso, presumido o payaso",
      "Enojarse cuando alguien cuenta un chiste",
      "Hablar de manera excesivamente formal",
    ],
  },
  {
    id: 16,
    term: "Careta",
    emoji: "🎭",
    sentence: "Resultó ser un careta que hablaba mal de mí a mis espaldas.",
    answer: "Una persona falsa o hipócrita",
    options: [
      "Una persona demasiado tímida",
      "Alguien que siempre dice lo que piensa",
      "Una persona falsa o hipócrita",
      "Alguien que trabaja como actor",
    ],
  },
  {
    id: 17,
    term: "Chorro",
    highlight: "chorros",
    emoji: "🚲",
    sentence: "Le robaron la bicicleta de la puerta de su casa; está lleno de chorros últimamente.",
    answer: "Ladrones",
    options: [
      "Policías que patrullan el barrio",
      "Personas que reparan bicicletas",
      "Vecinos que hacen mucho ruido",
      "Ladrones",
    ],
  },
  {
    id: 18,
    term: "Compa",
    highlight: "compas",
    emoji: "🎵",
    sentence: "Con mis compas siempre escuchamos música.",
    answer: "Compañeros o amigos",
    options: [
      "Compañeros o amigos",
      "Músicos profesionales",
      "Familiares que viven juntos",
      "Personas con gustos opuestos",
    ],
  },
  {
    id: 19,
    term: "Alto",
    emoji: "🤦",
    sentence: "Al final el tipo era alto bobo.",
    answer: "Un intensificador equivalente a gran o tremendo",
    options: [
      "Una referencia literal a su estatura",
      "Un intensificador equivalente a gran o tremendo",
      "Una manera de indicar que hablaba fuerte",
      "Una orden para que dejara de moverse",
    ],
  },
  {
    id: 20,
    term: "Salame",
    emoji: "🚪",
    sentence: "El guardia de seguridad del boliche era un tipo re salame.",
    answer: "Una persona tonta o poco despierta",
    options: [
      "Una persona agresiva y peligrosa",
      "Alguien serio que cumple bien su trabajo",
      "Una persona tonta o poco despierta",
      "Una persona alta y corpulenta",
    ],
  },
  {
    id: 21,
    term: "Salado",
    emoji: "🥶",
    sentence: "Está salado el frío que hace hoy en la rambla, abrigate bien.",
    answer: "Muy intenso, fuerte o difícil de soportar",
    options: [
      "Agradable para caminar sin abrigo",
      "Producido directamente por el agua del mar",
      "Inesperado pero de poca duración",
      "Muy intenso, fuerte o difícil de soportar",
    ],
  },
  {
    id: 22,
    term: "Imponente",
    emoji: "🎸",
    sentence: "El recital de anoche estuvo imponente, tocaron todas las clásicas.",
    answer: "Impresionante o excelente",
    options: [
      "Impresionante o excelente",
      "Demasiado corto para disfrutarlo",
      "Desorganizado y con mal sonido",
      "Correcto, aunque poco memorable",
    ],
  },
  {
    id: 23,
    term: "Macanudo",
    emoji: "👴",
    sentence: "El vecino del quinto piso es un veterano re macanudo.",
    answer: "Amable, buena persona o agradable",
    options: [
      "Malhumorado y poco sociable",
      "Amable, buena persona o agradable",
      "Ingenuo y fácil de engañar",
      "Hablador y difícil de interrumpir",
    ],
  },
  {
    id: 24,
    term: "Bárbaro",
    emoji: "✈️",
    sentence: "Me parece bárbaro que te vayas de viaje a conocer Europa.",
    answer: "Excelente o muy bueno",
    options: [
      "Peligroso e irresponsable",
      "Sorprendente pero inconveniente",
      "Excelente o muy bueno",
      "Costoso y difícil de organizar",
    ],
  },
  {
    id: 25,
    term: "Copado",
    emoji: "📚",
    sentence: "El profesor de historia es re copado y hace que las clases pasen volando.",
    answer: "Agradable, divertido o buena onda",
    options: [
      "Muy exigente con las calificaciones",
      "Experto únicamente en historia antigua",
      "Desordenado al explicar los temas",
      "Agradable, divertido o buena onda",
    ],
  },
  {
    id: 26,
    term: "Zarpado",
    emoji: "🏙️",
    sentence: "El precio de los alquileres en el centro de Montevideo está zarpado.",
    answer: "Excesivo, desmedido o extremadamente alto",
    options: [
      "Excesivo, desmedido o extremadamente alto",
      "Más barato que en otros barrios",
      "Fijo y controlado por el Estado",
      "Difícil de calcular con exactitud",
    ],
  },
  {
    id: 27,
    term: "Fisura",
    emoji: "🤕",
    sentence: "El domingo me levanté con una fisura tremenda y no salí de la cama en todo el día.",
    answer: "Una resaca o malestar fuerte después de salir",
    options: [
      "Una lesión causada por hacer deporte",
      "Una resaca o malestar fuerte después de salir",
      "Una preocupación por el trabajo del lunes",
      "Un cansancio normal después de dormir poco",
    ],
  },
  {
    id: 28,
    term: "Ni en pedo",
    emoji: "🚗",
    sentence: "Ni en pedo te presto el auto de nuevo después del choque del mes pasado.",
    answer: "De ninguna manera",
    options: [
      "Solamente si pagás la nafta",
      "Cuando se pase el enojo",
      "De ninguna manera",
      "Sin pensarlo demasiado",
    ],
  },
  {
    id: 29,
    term: "Banda",
    emoji: "⛈️",
    sentence: "Con esta tormenta eléctrica hubo una banda de relámpagos.",
    answer: "Una gran cantidad",
    options: [
      "Una serie de sonidos musicales",
      "Un único relámpago muy fuerte",
      "Un grupo organizado de meteorólogos",
      "Una gran cantidad",
    ],
  },
  {
    id: 30,
    term: "Embole",
    emoji: "😴",
    sentence: "La película era un embole total; me dormí a la media hora de haber empezado.",
    answer: "Algo muy aburrido",
    options: [
      "Algo muy aburrido",
      "Una historia difícil de comprender",
      "Una película demasiado larga",
      "Algo triste pero interesante",
    ],
  },
  {
    id: 31,
    term: "Bondi",
    emoji: "🚌",
    sentence: "Tuve que correr tres cuadras, pero por suerte alcancé el bondi.",
    answer: "El ómnibus",
    options: [
      "El taxi",
      "El ómnibus",
      "El tren",
      "El semáforo",
    ],
  },
  {
    id: 32,
    term: "Championes",
    emoji: "👟",
    sentence: "Me compré unos championes nuevos para empezar a salir a correr de mañana.",
    answer: "Calzado deportivo",
    options: [
      "Medias para hacer deporte",
      "Pantalones cortos",
      "Calzado deportivo",
      "Plantillas ortopédicas",
    ],
  },
  {
    id: 33,
    term: "Boludo",
    emoji: "🔥",
    sentence: "Poné la caldera en el fuego, no seas boludo.",
    answer: "Tonto o distraído",
    options: [
      "Demasiado apurado",
      "Experto preparando mate",
      "Enojado por tener que cocinar",
      "Tonto o distraído",
    ],
  },
  {
    id: 34,
    term: "Vamo arriba",
    emoji: "💪",
    sentence: "¡Vamo arriba, que todavía queda tiempo para empatar el partido!",
    answer: "Una expresión de ánimo o aliento",
    options: [
      "Una expresión de ánimo o aliento",
      "Una orden para subir a otro piso",
      "Una señal para abandonar el partido",
      "Una queja contra el árbitro",
    ],
  },
  {
    id: 35,
    term: "Bizcocho",
    highlight: "bizcochos",
    emoji: "🥐",
    sentence: "Fui a la panadería y traje medio kilo de bizcochos de queso y margaritas.",
    answer: "Una pieza pequeña de panadería, dulce o salada",
    options: [
      "Un tipo de sándwich caliente",
      "Una pieza pequeña de panadería, dulce o salada",
      "Una torta servida únicamente en cumpleaños",
      "Una galleta industrial envasada",
    ],
  },
  {
    id: 36,
    term: "Chivito",
    emoji: "🥩",
    sentence: "Al mediodía fuimos al bar de la esquina y nos pedimos un chivito al plato para compartir.",
    answer: "Un plato uruguayo cuyo ingrediente principal suele ser carne vacuna",
    options: [
      "Un guiso preparado con carne de cabra",
      "Una picada compuesta solamente por quesos",
      "Un plato uruguayo cuyo ingrediente principal suele ser carne vacuna",
      "Una porción de pescado con ensalada",
    ],
  },
  {
    id: 37,
    term: "Mango",
    emoji: "🪙",
    sentence: "A fin de mes siempre ando sin un mango partido al medio.",
    answer: "Dinero",
    options: [
      "Comida",
      "Tiempo libre",
      "Cambio para el ómnibus exclusivamente",
      "Dinero",
    ],
  },
  {
    id: 38,
    term: "Guita",
    emoji: "💻",
    sentence: "Esa computadora cuesta mucha guita; no me da el presupuesto en este momento.",
    answer: "Dinero",
    options: [
      "Dinero",
      "Energía eléctrica",
      "Memoria de almacenamiento",
      "Trabajo de reparación",
    ],
  },
  {
    id: 39,
    term: "Pinta",
    emoji: "🍖",
    sentence: "Tiene tremenda pinta ese asado que estás preparando en el parrillero.",
    answer: "Un aspecto muy apetitoso o atractivo",
    options: [
      "Una cantidad insuficiente de comida",
      "Un aspecto muy apetitoso o atractivo",
      "Un olor fuerte a comida quemada",
      "Una receta difícil de preparar",
    ],
  },
  {
    id: 40,
    term: "Jeta",
    emoji: "🚪",
    sentence: "Se enojó tanto que le cerró la puerta en la jeta.",
    answer: "La cara",
    options: [
      "La mano",
      "La espalda",
      "La cara",
      "La casa",
    ],
  },
  {
    id: 41,
    term: "Chamuyero",
    emoji: "🗣️",
    sentence: "No le creas nada de lo que te promete; es un chamuyero de primera.",
    answer: "Alguien que habla para convencer, seducir o engañar",
    options: [
      "Alguien que cumple todo lo que promete",
      "Una persona que habla muy poco",
      "Alguien que evita dar su opinión",
      "Alguien que habla para convencer, seducir o engañar",
    ],
  },
  {
    id: 42,
    term: "Zafar",
    emoji: "🏃",
    sentence: "Por suerte pude zafar de la reunión del consorcio porque tenía que trabajar hasta tarde.",
    answer: "Evitar o librarse de una situación",
    options: [
      "Evitar o librarse de una situación",
      "Llegar tarde sin avisar",
      "Cambiar una reunión de lugar",
      "Aceptar una obligación con desgano",
    ],
  },
  {
    id: 43,
    term: "Tranza",
    emoji: "📄",
    sentence: "Hacer todos los trámites de importación en la aduana es una tranza interminable.",
    answer: "Una complicación molesta, larga o tediosa",
    options: [
      "Un negocio rápido y beneficioso",
      "Una complicación molesta, larga o tediosa",
      "Un trámite que puede hacerse por internet",
      "Una negociación ilegal necesariamente",
    ],
  },
  {
    id: 44,
    term: "Quemarse",
    highlight: "quemar",
    emoji: "😡",
    sentence: "Se va a quemar muchísimo cuando vea que le rompiste el celular.",
    answer: "Enojarse mucho",
    options: [
      "Sentir vergüenza frente a otras personas",
      "Lastimarse físicamente con calor",
      "Enojarse mucho",
      "Preocuparse por el precio del arreglo",
    ],
  },
  {
    id: 45,
    term: "Ligar",
    highlight: "ligando",
    emoji: "🎲",
    sentence: "Fui sin estudiar nada al examen parcial y terminé ligando un seis de pura suerte.",
    answer: "Tener suerte o recibir algo favorable",
    options: [
      "Copiar las respuestas de otra persona",
      "Convencer al profesor para repetir la prueba",
      "Aprobar gracias a una buena preparación",
      "Tener suerte o recibir algo favorable",
    ],
  },
  {
    id: 46,
    term: "Palmar",
    emoji: "🥵",
    sentence: "Con este calor y sin aire acondicionado vamos a palmar todos acá adentro.",
    answer: "Morir, generalmente usado de manera exagerada",
    options: [
      "Morir, generalmente usado de manera exagerada",
      "Dormirse por el cansancio",
      "Irse del lugar antes de tiempo",
      "Empezar a transpirar",
    ],
  },
  {
    id: 47,
    term: "Relajo",
    emoji: "🧸",
    sentence: "Los niños dejaron el cuarto del fondo hecho un relajo después de jugar toda la tarde.",
    answer: "Un gran desorden",
    options: [
      "Un lugar preparado para descansar",
      "Un gran desorden",
      "Una reunión muy divertida",
      "Un juego inventado por los niños",
    ],
  },
  {
    id: 48,
    term: "Curro",
    emoji: "💸",
    sentence: "Vender esos cursos mágicos de inversión por internet es un curro bárbaro.",
    answer: "Un negocio engañoso o de dudosa honestidad",
    options: [
      "Un trabajo difícil pero legítimo",
      "Una inversión con ganancias aseguradas",
      "Un negocio engañoso o de dudosa honestidad",
      "Un curso gratuito financiado por publicidad",
    ],
  },
  {
    id: 49,
    term: "Dar pelota",
    highlight: "da pelota",
    emoji: "👂",
    sentence: "Le expliqué tres veces cómo funciona el programa, pero no me da pelota.",
    answer: "Prestar atención o hacer caso",
    options: [
      "Pedir que le expliquen nuevamente",
      "Jugar mientras otra persona trabaja",
      "Responder de manera agresiva",
      "Prestar atención o hacer caso",
    ],
  },
  {
    id: 50,
    term: "Garra",
    emoji: "🏆",
    sentence: "El equipo perdía dos a cero en el primer tiempo y lo terminó empatando poniendo mucha garra.",
    answer: "Esfuerzo, coraje y determinación",
    options: [
      "Esfuerzo, coraje y determinación",
      "Una estrategia puramente defensiva",
      "Suerte en los minutos finales",
      "Juego brusco y muchas faltas",
    ],
  },
];
